export const postsTypes = {
    FETCH_POSTS_LOADING:"FETCH_POSTS_LOADING",
    FETCH_POSTS_LOADED:"FETCH_POSTS_LOADED",
    FETCH_POSTS_ERRORS:"FETCH_POSTS_ERRORS",
    /////////////////////
    FETCH_TAGS_LOADING:"FETCH_TAGS_LOADING",
    FETCH_TAGS_LOADED:"FETCH_TAGS_LOADED",
    FETCH_TAGS_ERRORS:"FETCH_TAGS_ERRORS",
 
    FETCH_POSTS_BYUSER:"FETCH_POSTS_BYUSER",
    ///////////////
    FETCH_TAGS:"FETCH_TAGS",
    DELETE_POST:"DELETE_POST"
}
