export const commentsTypes = {
    FETCH_COMMENTS_LOADING:"FETCH_COMMENTS_LOADING",
    FETCH_COMMENTS_LOADED:"FETCH_COMMENTS_LOADED",
    FETCH_COMMENTS_ERROR:"FETCH_COMMENTS_ERROR",
    /////////////////////
    FETCH_CURRENTCOMMENTS_ERROR:"FETCH_CURRENTCOMMENTS_ERROR",
    FETCH_CURRENTCOMMENTS_LOADED:"FETCH_CURRENTCOMMENTS_LOADED",
    FETCH_CURRENTCOMMENTS_LOADING:"FETCH_CURRENTCOMMENTS_LOADING",
    ///////////////
    DELETE_COMMENT:"DELETE_COMMENT",
    CREATE_COMMENT:"CREATE_COMMENT"
}
