export const authTypes = {
    USER_REGISTER:"USER_REGISTER",
    FETCH_AUTH_DATA:"FETCH_AUTH_DATA",
    FETCH_LOGIN_USER:"FETCH_LOGIN_USER",
    AUTH_DATA_LOADED:"FETCH_AUTH_DATA_LOADED",
    AUTH_DATA_ERRORS:"FETCH_AUTH_DATA_ERRORS",
    USER_LOGOUT:"USER_LOGOUT",
    ///////////////
    FETCH_TAGS:"FETCH_TAGS",
    DELETE_POST:"DELETE_POST"
}