export const authTypes = {
  USER_REGISTER: "USER_REGISTER",
  FETCH_AUTH_DATA: "FETCH_AUTH_DATA",
  FETCH_LOGIN_USER: "FETCH_LOGIN_USER",
  AUTH_DATA_LOADED: "AUTH_DATA_LOADED",
  AUTH_DATA_ERRORS: "AUTH_DATA_ERRORS",
  USER_LOGOUT: "USER_LOGOUT",

  USER_LOGIN_REGISTER_ERRORS: "USER_LOGIN_REGISTER_ERRORS",

  ADD_USER_DISLIKE: "ADD_USER_DISLIKE",
  ADD_USER_LIKE: "ADD_USER_LIKE",

  UPDATE_USER_INFO: "UPDATE_USER_INFO",

  ///////////////
  FETCH_TAGS: "FETCH_TAGS",
  DELETE_POST: "DELETE_POST",
  CLEAR_STORE: "CLEAR_STORE"
}